Add new packages to the installation

diff --git a/Tools/lammps/build b/Tools/lammps/build
--- a/Tools/lammps/build
+++ b/Tools/lammps/build
@@ -1,40 +1,82 @@
 #!/usr/bin/env modbuild
 
 pbuild::pre_configure() {
-   echo "> Setting performance system compiler flags"
-   case "$(uname -m)" in
-       aarch64)
-           export CC=gcc
-           export CXX=g++
-           export CFLAGS='-march=native -O3 -pipe -Wno-error'
-           export CXXFLAGS='-march=native -O3 -pipe -Wno-error'
-           export FFLAGS='-march=native -O3 -pipe'
-           export FCFLAGS='-march=native -O3 -pipe'
-           export LDFLAGS='-Wl,--as-needed'
-           ;;
-       x86_64)
-           export CC=gcc
-           export CXX=g++
-           export CFLAGS='-march=znver2 -mtune=znver2 -O3 -pipe -Wno-error'
-           export CXXFLAGS='-march=znver2 -mtune=znver2 -O3 -pipe -Wno-error'
-           export FFLAGS='-march=znver2 -mtune=znver2 -O3 -pipe'
-           export FCFLAGS='-march=znver2 -mtune=znver2 -O3 -pipe'
-           export LDFLAGS='-Wl,--as-needed'
-           ;;
-       *)
-           echo ">> Unknown system architecture $(uname -m). Using default flags."
-           export CC=gcc
-           export CXX=g++
-           export CFLAGS='-O3 -pipe -Wno-error'
-           export CXXFLAGS='-O3 -pipe -Wno-error'
-           export FFLAGS='-O3 -pipe'
-           export FCFLAGS='-O3 -pipe'
-           export LDFLAGS='-Wl,--as-needed'
-           ;;
-   esac
+
+    echo "> Setting performance system compiler flags"
+
+    case "$(uname -m)" in
+        aarch64)
+            export CC=gcc
+            export CXX=g++
+
+            export CFLAGS='-march=native -O3 -pipe -Wno-error'
+            export CXXFLAGS='-march=native -O3 -pipe -Wno-error'
+            export FFLAGS='-march=native -O3 -pipe'
+            export FCFLAGS='-march=native -O3 -pipe'
+            export LDFLAGS='-Wl,--as-needed'
+
+            export GPU_ARCH='sm_90'
+
+            export Kokkos_ARCH_ZEN3='no'
+            export Kokkos_ARCH_AMPERE80='no'
+            export Kokkos_ARCH_HOPPER90='yes'
+            export Kokkos_ARCH_ARMV9_GRACE='yes'
+            ;;
+
+        x86_64)
+            export CC=gcc
+            export CXX=g++
+
+            export CFLAGS='-march=znver2 -mtune=znver2 -O3 -pipe -Wno-error'
+            export CXXFLAGS='-march=znver2 -mtune=znver2 -O3 -pipe -Wno-error'
+            export FFLAGS='-march=znver2 -mtune=znver2 -O3 -pipe'
+            export FCFLAGS='-march=znver2 -mtune=znver2 -O3 -pipe'
+            export LDFLAGS='-Wl,--as-needed'
+
+            export GPU_ARCH='sm_80'
+
+            export Kokkos_ARCH_ZEN3='yes'
+            export Kokkos_ARCH_AMPERE80='yes'
+            export Kokkos_ARCH_HOPPER90='no'
+            export Kokkos_ARCH_ARMV9_GRACE='no'
+            ;;
+
+        *)
+            echo "ERROR: Unsupported architecture: $(uname -m)" >&2
+            return 1
+            ;;
+    esac
+
+    # PLUMED PKG config path
+    export PKG_CONFIG_PATH="/opt/psi/overlays/Alps/Tools/plumed/2.10.1/lib/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}"
 }
 
 pbuild::configure() {
+    local extra_args=()
+
+    echo "PREFIX is: ${PREFIX}"
+    if [[ "$PREFIX" =~ _kokkos/$ ]]; then
+        extra_args+=(
+            -DPKG_KOKKOS=yes
+            -DKokkos_ENABLE_CUDA=yes
+            -DKokkos_ENABLE_OPENMP=yes
+            -DKokkos_ARCH_ZEN3="${Kokkos_ARCH_ZEN3}"
+            -DKokkos_ARCH_AMPERE80="${Kokkos_ARCH_AMPERE80}"
+            -DKokkos_ARCH_HOPPER90="${Kokkos_ARCH_HOPPER90}"
+            -DKokkos_ARCH_ARMV9_GRACE="${Kokkos_ARCH_ARMV9_GRACE}"
+            -DFFT_KOKKOS=CUFFT
+        )
+    else
+        extra_args+=(
+            -DPKG_KOKKOS=no
+            -DPKG_GPU=yes
+            -DGPU_API=cuda
+            -DGPU_ARCH="${GPU_ARCH}"
+            -DCUDA_BUILD_MULTIARCH=no
+            -DGPU_DEBUG=yes
+        )
+    fi
+
     cmake \
         -DCMAKE_INSTALL_PREFIX="${PREFIX}" \
         -DCMAKE_BUILD_TYPE=Release \
@@ -45,5 +87,27 @@ pbuild::configure() {
         -DCMAKE_Fortran_FLAGS="${FFLAGS}" \
         -DCMAKE_EXE_LINKER_FLAGS="${LDFLAGS}" \
         -DCMAKE_SHARED_LINKER_FLAGS="${LDFLAGS}" \
+        -DBUILD_MPI=yes \
+        -DBUILD_OMP=yes \
+        -DPKG_MOLECULE=yes \
+        "${extra_args[@]}" \
+        -DPKG_PLUMED=yes \
+        -DDOWNLOAD_PLUMED=no \
+        -DPLUMED_MODE=runtime \
+        -DPKG_ML-IAP=yes \
+        -DPKG_ML-SNAP=yes \
+        -DMLIAP_ENABLE_PYTHON=no \
+        -DPKG_COMPRESS=yes \
+        -DPKG_H5MD=yes \
+        -DPKG_PYTHON=no \
+        -DWITH_FENIX=yes \
+        -DPKG_KSPACE=yes \
+        -DPKG_ELECTRODE=yes \
+        -DPKG_RIGID=yes \
+        -DPKG_EXTRA-DUMP=yes \
+        -DPKG_GRAPHICS=yes \
+        -DWITH_JPEG=yes \
+        -DWITH_PNG=yes \
+        -DWITH_FFMPEG=no \
         "${SRC_DIR}/cmake"
 }
